## Clock signal
set_property PACKAGE_PIN W5 [get_ports clk_100MHz]
set_property IOSTANDARD LVCMOS33 [get_ports clk_100MHz]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports clk_100MHz]

## Player 1 Buttons
set_property PACKAGE_PIN T17 [get_ports up]
set_property IOSTANDARD LVCMOS33 [get_ports up]
set_property PACKAGE_PIN U17 [get_ports down]
set_property IOSTANDARD LVCMOS33 [get_ports down]
set_property PACKAGE_PIN U18 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset]

## Player 2 Buttons
set_property PACKAGE_PIN T18 [get_ports w]
set_property IOSTANDARD LVCMOS33 [get_ports w]
set_property PACKAGE_PIN W19 [get_ports s]
set_property IOSTANDARD LVCMOS33 [get_ports s]

## VGA Connector (RGB + Sync signals)
set_property PACKAGE_PIN G19 [get_ports {rgb[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[0]}]
set_property PACKAGE_PIN H19 [get_ports {rgb[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[1]}]
set_property PACKAGE_PIN J19 [get_ports {rgb[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[2]}]
set_property PACKAGE_PIN N19 [get_ports {rgb[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[3]}]
set_property PACKAGE_PIN J17 [get_ports {rgb[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[4]}]
set_property PACKAGE_PIN H17 [get_ports {rgb[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[5]}]
set_property PACKAGE_PIN G17 [get_ports {rgb[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[6]}]
set_property PACKAGE_PIN D17 [get_ports {rgb[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[7]}]
set_property PACKAGE_PIN N18 [get_ports {rgb[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[8]}]
set_property PACKAGE_PIN L18 [get_ports {rgb[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[9]}]
set_property PACKAGE_PIN K18 [get_ports {rgb[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[10]}]
set_property PACKAGE_PIN J18 [get_ports {rgb[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[11]}]

## VGA Sync Pins
set_property PACKAGE_PIN P19 [get_ports hsync]
set_property IOSTANDARD LVCMOS33 [get_ports hsync]
set_property PACKAGE_PIN R19 [get_ports vsync]
set_property IOSTANDARD LVCMOS33 [get_ports vsync]

# Ultrasonic sensor pins (assign to Pmod connector)

## Seven segment display segments
# set_property PACKAGE_PIN W7 [get_ports {seg[0]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {seg[0]}]
# set_property PACKAGE_PIN W6 [get_ports {seg[1]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {seg[1]}]
# set_property PACKAGE_PIN U8 [get_ports {seg[2]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {seg[2]}]
# set_property PACKAGE_PIN V8 [get_ports {seg[3]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {seg[3]}]
# set_property PACKAGE_PIN U5 [get_ports {seg[4]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {seg[4]}]
# set_property PACKAGE_PIN V5 [get_ports {seg[5]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {seg[5]}]
# set_property PACKAGE_PIN U7 [get_ports {seg[6]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {seg[6]}]

## Seven segment display anodes
# set_property PACKAGE_PIN U2 [get_ports {an[0]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {an[0]}]
# set_property PACKAGE_PIN U4 [get_ports {an[1]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {an[1]}]
# set_property PACKAGE_PIN V4 [get_ports {an[2]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {an[2]}]
# set_property PACKAGE_PIN W4 [get_ports {an[3]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {an[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {ir_sens[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ir_sens[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ir_sens[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ir_sens[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ir_sens[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ir_sens[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ir_sens[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ir_sens[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ir_sens[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ir_sens2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ir_sens2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ir_sens2[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ir_sens2[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ir_sens2[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ir_sens2[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ir_sens2[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ir_sens2[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ir_sens2[8]}]

set_property PACKAGE_PIN J3 [get_ports {ir_sens[0]}]
set_property PACKAGE_PIN L3 [get_ports {ir_sens[1]}]
set_property PACKAGE_PIN M2 [get_ports {ir_sens[2]}]
set_property PACKAGE_PIN N2 [get_ports {ir_sens[3]}]
set_property PACKAGE_PIN K3 [get_ports {ir_sens[4]}]
set_property PACKAGE_PIN M3 [get_ports {ir_sens[5]}]
set_property PACKAGE_PIN M1 [get_ports {ir_sens[6]}]
set_property PACKAGE_PIN N1 [get_ports {ir_sens[7]}]
set_property PACKAGE_PIN J1 [get_ports {ir_sens[8]}]
set_property PACKAGE_PIN K17 [get_ports {ir_sens2[0]}]
set_property PACKAGE_PIN M18 [get_ports {ir_sens2[1]}]
set_property PACKAGE_PIN N17 [get_ports {ir_sens2[2]}]
set_property PACKAGE_PIN P18 [get_ports {ir_sens2[3]}]
set_property PACKAGE_PIN L17 [get_ports {ir_sens2[4]}]
set_property PACKAGE_PIN M19 [get_ports {ir_sens2[5]}]
set_property PACKAGE_PIN P17 [get_ports {ir_sens2[6]}]
set_property PACKAGE_PIN R18 [get_ports {ir_sens2[7]}]
set_property PACKAGE_PIN A14 [get_ports {ir_sens2[8]}]
